### ISSUE TITLE
Test failure on the macOS GHC 8.8 run, no /proc

### ISSUE THREAD

**Issue by layus** [haskell-nix/hnix-store#109] opened 2021-01-08 09:19 UTC
```
  streamManyFilesToNar:   ls: cannot access '/proc/3496/fd': No such file or directory
FAIL (0.74s)
```

Example: https://github.com/haskell-nix/hnix/pull/810/checks?check_run_id=1665897143

**Comment by sorki** [comment] 2021-01-08 11:41
Test is using this to check file descriptor counts before and after NAR streaming - https://github.com/haskell-nix/hnix-store/blob/master/hnix-store-core/tests/NarFormat.hs#L366-L372

No `/proc` in CI VMs?

**Comment by Anton-Latukha** [comment] 2021-01-08 11:44
> I opened #108 to track it.

Regarding the `nix-store` not present - I checked that `nix` and `nix-store` are in the path during the build.

**Comment by Anton-Latukha** [comment] 2021-01-08 11:47
Just to remind. Apple does things and hoards money, and we need to adjust :laughing:

I am aware on any macOS changes and happening only through the CI.

**Comment by Anton-Latukha** [comment] 2021-01-11 19:12
The underlying idea of me transferring testing, report & making a joke here is this:

Our projects are interlinked, so we should move more testing upstream. And with the support, we must determine all together, what we include in the support and who has interest / sort of agrees to track and fix things.

We must decide what to do with macOS support. And macOS platform is changing, we know.

Now macOS platform is already in the transition. And after the transition it is obvious it would be more tighter and tighter in a proprietary way, and more and more different from Linux.

My view is: I personally, do not know specifics of or own any macOS devices. `sorki` most probably the same way.
But I agree that macOS is a big platform with a lot of devs, Haskell devs & some Nix people sitting on it. John AFAIK used macOS.
I think the bare minimum - we should test & support classical Haskell development for the projects on macOS. So Hackage & Cabal development works on macOS. That is a minimum requirement we can supply to the platform.
The Nix dev env on macOS depends on Nixpkgs situations & support of it. We probably can support macOS, but it would've been great if there was people who was interested in refactoring the projects to support it & maintaining the software stack for the platform. I personally (at all) not very interested in Nix dev env on macOS.

But whatever choice of support we do - we must do it together. I propose to introduce a Hackage Cabal macOS test. But about Nix dev env I would tag along for any team decigion and would stay unaffectionate about the Nix dev env for macOS.
I'd at the very minimum deferred the Nix dev env for macOS from the PR check to the `master` scheduled check. And probably'd removed the Nix dev env for macOS CI check fully, until someone would be interested in it. HLS + Hackage Cabal macOS workflow if fully enough for very good development of the project. If there is no devs interested in Nix dev env on macOS - why we keep checking it in every PR?

**Comment by layus** [comment] 2021-01-12 08:55
Oh, macos has no /proc. This was a real surprise. See https://superuser.com/questions/631693/where-is-the-proc-folder-on-mac-os-x

I am not at all interested in striving to support macos. But in this case I guess we can just disable that test on that platform until someone fixes it.

**Comment by Anton-Latukha** [comment] 2021-01-12 13:43
Ok.

I understood.

The question I raised is that the projects have to pick the support together. Because what Store supports - means that downstream can support only that also.

Moving there (my) messages to direct topic.

**Comment by marsam** [comment] 2021-03-12 14:26
Hi, are there any plans to cut a new release soon? without this patch hnix-store-core is broken on nix darwin.

**Comment by Anton-Latukha** [comment] 2021-03-12 17:58
Doing the relese, but stopped, since `remote` is also broken for `darwin`: https://github.com/haskell-nix/hnix-store/pull/114/checks?check_run_id=2097396100

I restarted the build, but it would reproducibly reappear, since `remote` uses `linux-headers` or something like that.

**Comment by Anton-Latukha** [comment] 2021-03-12 18:05
Well, lets do Core release then.

**Comment by Anton-Latukha** [comment] 2021-03-12 18:27
@marsam, releases are out to Hackage.

But with the default `-fprof` flag 8)
This first time releasing projects in the pressing time, only Hackage notified me there is profiling enabled by default 8).

Next would upload the docs and stuff. But the most important for Nixpkgs is done.

**Comment by Anton-Latukha** [comment] 2021-03-12 18:29
@marsam: Releases done.

There are thing to clean-up afterwards, but the main thing for Nixpkgs is done.

**Comment by marsam** [comment] 2021-03-12 23:52
Cool, thank you!

**Comment by Anton-Latukha** [comment] 2021-03-13 22:27
Well, the strangeness of my previous actions here - is that GitHub was acting really weird, write actions were completely blocked, but were appearing 10 minutes after.

**Closed by Anton-Latukha** 2021-03-13 22:27 UTC
