### ISSUE TITLE
Nar uses lazy IO instead of streaming

### ISSUE THREAD

**Issue by domenkozar** [haskell-nix/hnix-store#51] opened 2019-08-19 14:49 UTC
Feed it a store path with lots of files and you end up with:

```
/nix/store/3m1hc2mrz6zhqng088s4fw0rzfb1g6qy-perl-5.28.1: getDirectoryContents:openDirStream: resource exhausted (Too many open files)
```

**Comment by roberth** [comment] 2019-08-19 15:06
The culprit: https://github.com/haskell-nix/hnix-store/blob/master/hnix-store-core/src/System/Nix/Nar.hs#L81-L88

One may also consider [`unix`'s bytestring directory functions](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Directory-ByteString.html), to match Nix more closely. For performance, it's best to [`getFileStatus`](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Files-ByteString.html#v:getFileStatus) once per path.

**Comment by shlevy** [comment] 2019-08-20 19:46
@imalsogreg Are you able to take a look?

**Comment by imalsogreg** [comment] 2019-08-21 01:30
Yeah - thanks for the analysis on this. I'll try to reproduce with a test and then fix with some combination of [streaming](http://hackage.haskell.org/package/streaming) and [unix](http://hackage.haskell.org/package/unix). Will update the ticket when I have a WIP branch.

**Comment by domenkozar** [comment] 2019-09-09 07:34
Relevant: https://github.com/haskell-nix/hnix-store/pull/52

**Comment by domenkozar** [comment] 2019-11-09 12:32
Hey @imalsogreg did you make some progress on this one?

**Comment by imalsogreg** [comment] 2019-11-11 02:07
@domenkozar Nope, attention's been elsewhere, but thanks for the bump.

**Comment by domenkozar** [comment] 2020-03-10 12:18
I'm happy to sponsor $150 for someone fixing this issue.

**Comment by imalsogreg** [comment] 2020-03-11 20:46
@domenkozar I've been focusing on this the past couple days, on the `vigorous-io` branch.

**Comment by sorki** [comment] 2021-03-24 08:30
Closing since this landed some time ago, it could use some real world testing! :smile:

**Closed by sorki** 2021-03-24 08:30 UTC
